label_mapping = {
    '0': 'chapathi',
    '1': 'rasagulla',
    '2': 'biriyani',
    '3': 'uttapam',
    '4': 'palak paneer',
    '5': 'poha',
    '6': 'khichdi',
    '7': 'omlet',
    '8': 'rice',
    '9': 'Daal makhni',
    '10': 'rajma',
    '11': 'poori',
    '12': 'channa masala',
    '13': 'daal',
    '14': 'sambar',
    '15': 'paapad',
    '16': 'gulab jamun',
    '17': 'idli',
    '18': 'vada',
    '19': 'dosa',
}
